export const READ_CUSTOMERS = "READ_CUSTOMERS";
export const READ_ONE_CUSTOMER = "READ_ONE_CUSTOMER";
export const CREATE_CUSTOMER = "CREATE_CUSTOMER";
export const UPDATE_CUSTOMER = "UPDATE_CUSTOMER";
export const CUSTOMER_ERROR = "CUSTOMER_ERROR";
export const CLEAR_CUSTOMER = "CLEAR_CUSTOMER";
export const START_CUSTOMERS_RELOAD = "START_CUSTOMERS_RELOAD";
export const FINISHED_CUSTOMERS_RELOAD = "FINISHED_CUSTOMERS_RELOAD";
