export const START_RELOAD = "START_RELOAD";
export const FINISHED_RELOAD = "FINISHED_RELOAD";
export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";

export const LOGIN = "LOGIN";
export const USER_LOADED = "USER_LOADED";
export const LOGOUT = "LOGOUT";
export const FORGET_PASSWORD = "FORGET_PASSWORD";
export const AUTH_ERROR = "AUTH_ERROR";
export const START_AUTH_RELOAD = "START_AUTH_RELOAD";
export const FINISHED_AUTH_RELOAD = "FINISHED_AUTH_RELOAD";
export const SET_TOKEN = "SET_TOKEN";
