export const READ_INVOICES = "READ_INVOICES";
export const READ_ONE_INVOICE = "READ_ONE_INVOICE";
export const INVOICE_ERROR = "INVOICE_ERROR";
export const CHANGE_INVOICE_STATUS = "CHANGE_INVOICE_STATUS";
export const START_INVOICES_RELOAD = "START_INVOICES_RELOAD";
export const FINISHED_INVOICES_RELOAD = "FINISHED_INVOICES_RELOAD";
export const CLEAR_INVOICE = "CLEAR_INVOICE";
