export const CREATE_ORDER = "CREATE_ORDER";
export const ORDER_ERROR = "ORDER_ERROR";
export const START_ORDERS_RELOAD = "START_ORDERS_RELOAD";
export const FINISHED_ORDERS_RELOAD = "FINISHED_ORDERS_RELOAD";
