export const READ_SETTINGS = "READ_SETTINGS";
export const UPDATE_SETTING = "UPDATE_SETTING";
export const SETTING_ERROR = "SETTING_ERROR";
export const CLEAR_SETTING = "CLEAR_SETTING";
export const START_SETTINGS_RELOAD = "START_SETTINGS_RELOAD";
export const FINISHED_SETTINGS_RELOAD = "FINISHED_SETTINGS_RELOAD";
